; Imported symbols
	.globalzp COLOR

; Exported symbols
	.export bytecode_start

	.include "target.inc"

; TOKENS:
	.importzp	TOK_0
	.importzp	TOK_1
	.importzp	TOK_BYTE
	.importzp	TOK_BYTE_PEEK
	.importzp	TOK_BYTE_POKE
	.importzp	TOK_CJUMP
	.importzp	TOK_CLOSE
	.importzp	TOK_CNJUMP
	.importzp	TOK_COMP_0
	.importzp	TOK_DPOKE
	.importzp	TOK_DRAWTO
	.importzp	TOK_END
	.importzp	TOK_EQ
	.importzp	TOK_FOR
	.importzp	TOK_FOR_EXIT
	.importzp	TOK_FOR_NEXT
	.importzp	TOK_GRAPHICS
	.importzp	TOK_IOCHN
	.importzp	TOK_LT
	.importzp	TOK_L_AND
	.importzp	TOK_L_OR
	.importzp	TOK_MUL
	.importzp	TOK_NUM
	.importzp	TOK_NUM_POKE
	.importzp	TOK_PMGRAPHICS
	.importzp	TOK_POSITION
	.importzp	TOK_PUSH_0
	.importzp	TOK_PUSH_1
	.importzp	TOK_PUSH_BYTE
	.importzp	TOK_PUSH_VAR_LOAD
	.importzp	TOK_PUT
	.importzp	TOK_VAR_LOAD
	.importzp	TOK_VAR_SADDR
;-----------------------------
; Macro to get variable ID from name
	.import __HEAP_RUN__
.macro makevar name
	.byte <((.ident (.concat ("fb_var_", name)) - __HEAP_RUN__)/2)
.endmacro
; Variables
	.segment "HEAP"
	.export fb_var_Y
fb_var_Y:	.res 2	; Word variable
	.export fb_var_X
fb_var_X:	.res 2	; Word variable
	.export fb_var_I
fb_var_I:	.res 2	; Word variable
;-----------------------------
; Bytecode
	.segment "BYTECODE"
bytecode_start:
@FastBasic_LINE_1:	; LINE 1
	.byte	TOK_0
	.byte	TOK_PMGRAPHICS
	.byte	TOK_BYTE
	.byte	6
	.byte	TOK_CLOSE
	.byte	TOK_BYTE
	.byte	23
	.byte	TOK_GRAPHICS
	.byte	TOK_BYTE
	.byte	26
	.byte	TOK_NUM_POKE
	.word	709
	.byte	TOK_BYTE
	.byte	42
	.byte	TOK_NUM_POKE
	.word	710
	.byte	TOK_BYTE
	.byte	58
	.byte	TOK_NUM_POKE
	.word	711
	.byte	TOK_0
	.byte	TOK_PUSH_0
	.byte	TOK_POSITION
	.byte	TOK_1
	.byte	TOK_BYTE_POKE
	.byte	COLOR
@FastBasic_LINE_2:	; LINE 2
	.byte	TOK_VAR_SADDR
	makevar	"Y"
	.byte	TOK_PUSH_0
	.byte	TOK_DPOKE
	.byte	TOK_BYTE
	.byte	91
	.byte	TOK_PUSH_1
	.byte	TOK_FOR
	.byte	TOK_CNJUMP
	.word	jump_lbl_1
jump_lbl_2:
	.byte	TOK_VAR_SADDR
	makevar	"X"
	.byte	TOK_PUSH_0
	.byte	TOK_DPOKE
	.byte	TOK_BYTE
	.byte	159
	.byte	TOK_PUSH_1
	.byte	TOK_FOR
	.byte	TOK_CNJUMP
	.word	jump_lbl_3
jump_lbl_4:
	.byte	TOK_BYTE
	.byte	3
	.byte	TOK_PUSH_VAR_LOAD
	makevar	"X"
	.byte	TOK_COMP_0
	.byte	TOK_PUSH_VAR_LOAD
	makevar	"Y"
	.byte	TOK_PUSH_1
	.byte	TOK_LT
	.byte	TOK_L_AND
	.byte	TOK_PUSH_VAR_LOAD
	makevar	"X"
	.byte	TOK_PUSH_VAR_LOAD
	makevar	"Y"
	.byte	TOK_EQ
	.byte	TOK_L_OR
	.byte	TOK_PUSH_VAR_LOAD
	makevar	"X"
	.byte	TOK_PUSH_BYTE
	.byte	80
	.byte	TOK_EQ
	.byte	TOK_L_OR
	.byte	TOK_PUSH_VAR_LOAD
	makevar	"Y"
	.byte	TOK_PUSH_BYTE
	.byte	140
	.byte	TOK_EQ
	.byte	TOK_L_OR
	.byte	TOK_MUL
	.byte	TOK_BYTE_POKE
	.byte	COLOR
	.byte	TOK_VAR_LOAD
	makevar	"X"
	.byte	TOK_PUSH_VAR_LOAD
	makevar	"Y"
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	6
	.byte	TOK_IOCHN
	.byte	TOK_BYTE_PEEK
	.byte	COLOR
	.byte	TOK_PUT
	.byte	TOK_0
	.byte	TOK_IOCHN
	.byte	TOK_FOR_NEXT
	.byte	TOK_CJUMP
	.word	jump_lbl_4
jump_lbl_3:
	.byte	TOK_FOR_EXIT
	.byte	TOK_FOR_NEXT
	.byte	TOK_CJUMP
	.word	jump_lbl_2
jump_lbl_1:
	.byte	TOK_FOR_EXIT
@FastBasic_LINE_3:	; LINE 3
	.byte	TOK_BYTE
	.byte	80
	.byte	TOK_PUSH_BYTE
	.byte	92
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	6
	.byte	TOK_IOCHN
	.byte	TOK_BYTE_PEEK
	.byte	COLOR
	.byte	TOK_PUT
	.byte	TOK_0
	.byte	TOK_IOCHN
	.byte	TOK_BYTE
	.byte	90
	.byte	TOK_PUSH_BYTE
	.byte	80
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	17
	.byte	TOK_DRAWTO
	.byte	TOK_BYTE
	.byte	100
	.byte	TOK_PUSH_BYTE
	.byte	92
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	17
	.byte	TOK_DRAWTO
	.byte	TOK_BYTE
	.byte	80
	.byte	TOK_PUSH_BYTE
	.byte	92
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	17
	.byte	TOK_DRAWTO
	.byte	TOK_BYTE
	.byte	80
	.byte	TOK_PUSH_BYTE
	.byte	80
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	17
	.byte	TOK_DRAWTO
@FastBasic_LINE_4:	; LINE 4
	.byte	TOK_BYTE
	.byte	80
	.byte	TOK_PUSH_BYTE
	.byte	25
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	6
	.byte	TOK_IOCHN
	.byte	TOK_BYTE_PEEK
	.byte	COLOR
	.byte	TOK_PUT
	.byte	TOK_0
	.byte	TOK_IOCHN
	.byte	TOK_BYTE
	.byte	85
	.byte	TOK_PUSH_BYTE
	.byte	20
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	17
	.byte	TOK_DRAWTO
	.byte	TOK_BYTE
	.byte	90
	.byte	TOK_PUSH_BYTE
	.byte	20
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	17
	.byte	TOK_DRAWTO
	.byte	TOK_BYTE
	.byte	85
	.byte	TOK_PUSH_BYTE
	.byte	25
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	17
	.byte	TOK_DRAWTO
	.byte	TOK_BYTE
	.byte	80
	.byte	TOK_PUSH_BYTE
	.byte	25
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	17
	.byte	TOK_DRAWTO
@FastBasic_LINE_5:	; LINE 5
	.byte	TOK_BYTE
	.byte	85
	.byte	TOK_PUSH_BYTE
	.byte	20
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	6
	.byte	TOK_IOCHN
	.byte	TOK_BYTE_PEEK
	.byte	COLOR
	.byte	TOK_PUT
	.byte	TOK_0
	.byte	TOK_IOCHN
	.byte	TOK_BYTE
	.byte	85
	.byte	TOK_PUSH_BYTE
	.byte	25
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	17
	.byte	TOK_DRAWTO
	.byte	TOK_BYTE
	.byte	91
	.byte	TOK_PUSH_BYTE
	.byte	22
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	6
	.byte	TOK_IOCHN
	.byte	TOK_BYTE_PEEK
	.byte	COLOR
	.byte	TOK_PUT
	.byte	TOK_0
	.byte	TOK_IOCHN
	.byte	TOK_BYTE
	.byte	91
	.byte	TOK_PUSH_BYTE
	.byte	23
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	17
	.byte	TOK_DRAWTO
	.byte	TOK_BYTE
	.byte	92
	.byte	TOK_PUSH_BYTE
	.byte	22
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	6
	.byte	TOK_IOCHN
	.byte	TOK_BYTE_PEEK
	.byte	COLOR
	.byte	TOK_PUT
	.byte	TOK_0
	.byte	TOK_IOCHN
	.byte	TOK_BYTE
	.byte	92
	.byte	TOK_PUSH_BYTE
	.byte	23
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	17
	.byte	TOK_DRAWTO
@FastBasic_LINE_6:	; LINE 6
	.byte	TOK_BYTE
	.byte	93
	.byte	TOK_PUSH_BYTE
	.byte	22
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	6
	.byte	TOK_IOCHN
	.byte	TOK_BYTE_PEEK
	.byte	COLOR
	.byte	TOK_PUT
	.byte	TOK_0
	.byte	TOK_IOCHN
	.byte	TOK_BYTE
	.byte	93
	.byte	TOK_PUSH_BYTE
	.byte	23
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	17
	.byte	TOK_DRAWTO
	.byte	TOK_BYTE
	.byte	94
	.byte	TOK_PUSH_BYTE
	.byte	22
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	6
	.byte	TOK_IOCHN
	.byte	TOK_BYTE_PEEK
	.byte	COLOR
	.byte	TOK_PUT
	.byte	TOK_0
	.byte	TOK_IOCHN
	.byte	TOK_BYTE
	.byte	94
	.byte	TOK_PUSH_BYTE
	.byte	23
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	17
	.byte	TOK_DRAWTO
	.byte	TOK_BYTE
	.byte	95
	.byte	TOK_PUSH_BYTE
	.byte	22
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	6
	.byte	TOK_IOCHN
	.byte	TOK_BYTE_PEEK
	.byte	COLOR
	.byte	TOK_PUT
	.byte	TOK_0
	.byte	TOK_IOCHN
	.byte	TOK_BYTE
	.byte	95
	.byte	TOK_PUSH_BYTE
	.byte	23
	.byte	TOK_POSITION
	.byte	TOK_BYTE
	.byte	17
	.byte	TOK_DRAWTO
@FastBasic_LINE_7:	; LINE 7
	.byte	TOK_VAR_SADDR
	makevar	"I"
	.byte	TOK_PUSH_1
	.byte	TOK_DPOKE
	.byte	TOK_NUM
	.word	5000
	.byte	TOK_PUSH_1
	.byte	TOK_FOR
	.byte	TOK_CNJUMP
	.word	jump_lbl_5
jump_lbl_6:
	.byte	TOK_FOR_NEXT
	.byte	TOK_CJUMP
	.word	jump_lbl_6
jump_lbl_5:
	.byte	TOK_FOR_EXIT
	.byte	TOK_0
	.byte	TOK_PMGRAPHICS
	.byte	TOK_BYTE
	.byte	6
	.byte	TOK_CLOSE
	.byte	TOK_0
	.byte	TOK_GRAPHICS
	.byte	TOK_END
