;
; File generated by cc65 v 2.18 - Ubuntu 2.18-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.18-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "ascii.c", 2312, 1615619520
	.dbg		file, "/usr/share/cc65/include/conio.h", 8941, 1573331006
	.dbg		file, "/usr/share/cc65/include/stdarg.h", 2913, 1573331006
	.dbg		file, "/usr/share/cc65/include/target.h", 2992, 1573331006
	.dbg		file, "/usr/share/cc65/include/atari.h", 21597, 1573331006
	.dbg		file, "/usr/share/cc65/include/_atarios.h", 41120, 1573331006
	.dbg		file, "/usr/share/cc65/include/_gtia.h", 13839, 1573331006
	.dbg		file, "/usr/share/cc65/include/_pbi.h", 3143, 1573331006
	.dbg		file, "/usr/share/cc65/include/_pokey.h", 11387, 1573331006
	.dbg		file, "/usr/share/cc65/include/_pia.h", 3044, 1573331006
	.dbg		file, "/usr/share/cc65/include/_antic.h", 11828, 1573331006
	.dbg		file, "/usr/share/cc65/include/stdio.h", 6189, 1573331006
	.dbg		file, "/usr/share/cc65/include/stddef.h", 3057, 1573331006
	.dbg		file, "/usr/share/cc65/include/stdlib.h", 5748, 1573331006
	.dbg		file, "/usr/share/cc65/include/stdbool.h", 2506, 1573331006
	.forceimport	__STARTUP__
	.dbg		sym, "clrscr", "00", extern, "_clrscr"
	.dbg		sym, "cputc", "00", extern, "_cputc"
	.dbg		sym, "cprintf", "00", extern, "_cprintf"
	.dbg		sym, "cgetc", "00", extern, "_cgetc"
	.dbg		sym, "cursor", "00", extern, "_cursor"
	.dbg		sym, "screensize", "00", extern, "_screensize"
	.import		_clrscr
	.import		_cputc
	.import		_cprintf
	.import		_cgetc
	.import		_cursor
	.import		_screensize
	.export		_main

.segment	"RODATA"

L002B:
	.byte	$54,$79,$70,$65,$20,$63,$68,$61,$72,$61,$63,$74,$65,$72,$73,$20
	.byte	$74,$6F,$20,$73,$65,$65,$0D,$9B,$74,$68,$65,$69,$72,$20,$68,$65
	.byte	$78,$61,$64,$65,$63,$69,$6D,$61,$6C,$20,$63,$6F,$64,$65,$0D,$9B
	.byte	$6E,$75,$6D,$62,$65,$72,$73,$20,$2D,$20,$27,$51,$27,$20,$71,$75
	.byte	$69,$74,$73,$3A,$0D,$9B,$9B,$00
L004C:
	.byte	$3D,$24,$25,$30,$32,$78,$20,$00
L005B:
	.byte	$0D,$9B,$00
L0055	:=	L005B+0

.segment	"BSS"

_height:
	.res	1,$00
_width:
	.res	1,$00
_r:
	.res	1,$00
_t:
	.res	1,$00
_c:
	.res	2,$00

; ---------------------------------------------------------------
; int __near__ GET (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_GET: near

	.dbg	func, "GET", "00", static, "_GET"

.segment	"CODE"

;
; PUT(c = (int)cgetc());
;
	.dbg	line, "ascii.c", 38
	jsr     _cgetc
	ldx     #$00
	sta     _c
	stx     _c+1
	jsr     _cputc
;
; return c;
;
	.dbg	line, "ascii.c", 39
	lda     _c
	ldx     _c+1
;
; }
;
	.dbg	line, "ascii.c", 40
	rts
	.dbg	line

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", extern, "_main"

.segment	"CODE"

;
; clrscr();
;
	.dbg	line, "ascii.c", 55
	jsr     _clrscr
;
; r = 7;                          /* allow for prompt */
;
	.dbg	line, "ascii.c", 56
	lda     #$07
	sta     _r
;
; PRINT("Type characters to see\r\ntheir hexadecimal code\r\nnumbers - 'Q' quits:\r\n\n");
;
	.dbg	line, "ascii.c", 61
	lda     #<(L002B)
	ldx     #>(L002B)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
;
; screensize(&width, &height);    /* get the screen's dimensions */
;
	.dbg	line, "ascii.c", 62
	lda     #<(_width)
	ldx     #>(_width)
	jsr     pushax
	lda     #<(_height)
	ldx     #>(_height)
	jsr     _screensize
;
; width /= 6;                     /* get number of codes on a line */
;
	.dbg	line, "ascii.c", 63
	lda     _width
	jsr     pusha0
	lda     #$06
	jsr     tosudiva0
	sta     _width
;
; cursor(true);
;
	.dbg	line, "ascii.c", 64
	lda     #$01
	jsr     _cursor
;
; while ((c = GET()) != EOF) {
;
	.dbg	line, "ascii.c", 66
	jmp     L0062
;
; if (r == height) {
;
	.dbg	line, "ascii.c", 69
L0036:	lda     _height
	cmp     _r
	bne     L003D
;
; clrscr();
;
	.dbg	line, "ascii.c", 70
	jsr     _clrscr
;
; t = 0;
;
	.dbg	line, "ascii.c", 71
	lda     #$00
	sta     _t
;
; PUT(c); /* echo char. again because screen was erased */
;
	.dbg	line, "ascii.c", 72
	lda     _c
	jsr     _cputc
;
; r = 1;
;
	.dbg	line, "ascii.c", 73
	lda     #$01
	sta     _r
;
; if (c == '\n')
;
	.dbg	line, "ascii.c", 75
L003D:	lda     _c+1
	bne     L0047
	lda     _c
	cmp     #$9B
	bne     L0047
;
; ++r;
;
	.dbg	line, "ascii.c", 76
	inc     _r
;
; PRINT("=$%02x ", c);
;
	.dbg	line, "ascii.c", 79
L0047:	lda     #<(L004C)
	ldx     #>(L004C)
	jsr     pushax
	lda     _c
	ldx     _c+1
	jsr     pushax
	ldy     #$04
	jsr     _cprintf
;
; if (c == QUIT)
;
	.dbg	line, "ascii.c", 80
	lda     _c+1
	bne     L0061
	lda     _c
	cmp     #$51
;
; break;
;
	.dbg	line, "ascii.c", 81
	beq     L0037
;
; if (++t == width) {
;
	.dbg	line, "ascii.c", 82
L0061:	inc     _t
	lda     _width
	cmp     _t
	bne     L0052
;
; PRINT("\r\n");
;
	.dbg	line, "ascii.c", 83
	lda     #<(L0055)
	ldx     #>(L0055)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
;
; ++r;
;
	.dbg	line, "ascii.c", 84
	inc     _r
;
; t = 0;
;
	.dbg	line, "ascii.c", 85
L0062:	lda     #$00
	sta     _t
;
; while ((c = GET()) != EOF) {
;
	.dbg	line, "ascii.c", 66
L0052:	jsr     _GET
	sta     _c
	stx     _c+1
	cpx     #$FF
	bne     L0036
	cmp     #$FF
	bne     L0036
;
; PRINT("\r\n");
;
	.dbg	line, "ascii.c", 88
L0037:	lda     #<(L005B)
	ldx     #>(L005B)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
;
; return EXIT_SUCCESS;
;
	.dbg	line, "ascii.c", 89
	ldx     #$00
	txa
;
; }
;
	.dbg	line, "ascii.c", 90
	rts
	.dbg	line

.endproc

