;
; File generated by cc65 v 2.18 - Ubuntu 2.18-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.18-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "hello.c", 1963, 1615619520
	.dbg		file, "/usr/share/cc65/include/stdlib.h", 5748, 1573331006
	.dbg		file, "/usr/share/cc65/include/string.h", 5104, 1573331006
	.dbg		file, "/usr/share/cc65/include/stddef.h", 3057, 1573331006
	.dbg		file, "/usr/share/cc65/include/conio.h", 8941, 1573331006
	.dbg		file, "/usr/share/cc65/include/stdarg.h", 2913, 1573331006
	.dbg		file, "/usr/share/cc65/include/target.h", 2992, 1573331006
	.dbg		file, "/usr/share/cc65/include/atari.h", 21597, 1573331006
	.dbg		file, "/usr/share/cc65/include/_atarios.h", 41120, 1573331006
	.dbg		file, "/usr/share/cc65/include/_gtia.h", 13839, 1573331006
	.dbg		file, "/usr/share/cc65/include/_pbi.h", 3143, 1573331006
	.dbg		file, "/usr/share/cc65/include/_pokey.h", 11387, 1573331006
	.dbg		file, "/usr/share/cc65/include/_pia.h", 3044, 1573331006
	.dbg		file, "/usr/share/cc65/include/_antic.h", 11828, 1573331006
	.dbg		file, "/usr/share/cc65/include/joystick.h", 5135, 1573331006
	.forceimport	__STARTUP__
	.dbg		sym, "strlen", "00", extern, "_strlen"
	.dbg		sym, "clrscr", "00", extern, "_clrscr"
	.dbg		sym, "gotoxy", "00", extern, "_gotoxy"
	.dbg		sym, "cputc", "00", extern, "_cputc"
	.dbg		sym, "cprintf", "00", extern, "_cprintf"
	.dbg		sym, "cgetc", "00", extern, "_cgetc"
	.dbg		sym, "bgcolor", "00", extern, "_bgcolor"
	.dbg		sym, "bordercolor", "00", extern, "_bordercolor"
	.dbg		sym, "chline", "00", extern, "_chline"
	.dbg		sym, "cvlinexy", "00", extern, "_cvlinexy"
	.dbg		sym, "screensize", "00", extern, "_screensize"
	.import		_strlen
	.import		_clrscr
	.import		_gotoxy
	.import		_cputc
	.import		_cprintf
	.import		_cgetc
	.import		_bgcolor
	.import		_bordercolor
	.import		_chline
	.import		_cvlinexy
	.import		_screensize
	.export		_main

.segment	"RODATA"

_Text:
	.byte	$48,$65,$6C,$6C,$6F,$20,$77,$6F,$72,$6C,$64,$21,$00
L005C:
	.byte	$25,$73,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", extern, "_main"
	.dbg	sym, "XSize", "00", auto, -1
	.dbg	sym, "YSize", "00", auto, -2

.segment	"CODE"

;
; (void) textcolor (COLOR_WHITE);
;
	.dbg	line, "hello.c", 38
	jsr     decsp2
;
; (void) bordercolor (COLOR_BLACK);
;
	.dbg	line, "hello.c", 39
	lda     #$00
	jsr     _bordercolor
;
; (void) bgcolor (COLOR_BLACK);
;
	.dbg	line, "hello.c", 40
	lda     #$00
	jsr     _bgcolor
;
; clrscr ();
;
	.dbg	line, "hello.c", 43
	jsr     _clrscr
;
; screensize (&XSize, &YSize);
;
	.dbg	line, "hello.c", 46
	lda     sp
	ldx     sp+1
	clc
	adc     #$01
	bcc     L0039
	inx
L0039:	jsr     pushax
	lda     sp
	ldx     sp+1
	clc
	adc     #$02
	bcc     L003B
	inx
L003B:	jsr     _screensize
;
; cputc (CH_ULCORNER);
;
	.dbg	line, "hello.c", 51
	lda     #$11
	jsr     _cputc
;
; chline (XSize - 2);
;
	.dbg	line, "hello.c", 52
	ldy     #$01
	lda     (sp),y
	sec
	sbc     #$02
	jsr     _chline
;
; cputc (CH_URCORNER);
;
	.dbg	line, "hello.c", 53
	lda     #$05
	jsr     _cputc
;
; cvlinexy (0, 1, YSize - 2);
;
	.dbg	line, "hello.c", 56
	jsr     decsp2
	lda     #$00
	ldy     #$01
	sta     (sp),y
	tya
	dey
	sta     (sp),y
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$02
	jsr     _cvlinexy
;
; cputc (CH_LLCORNER);
;
	.dbg	line, "hello.c", 59
	lda     #$1A
	jsr     _cputc
;
; chline (XSize - 2);
;
	.dbg	line, "hello.c", 60
	ldy     #$01
	lda     (sp),y
	sec
	sbc     #$02
	jsr     _chline
;
; cputc (CH_LRCORNER);
;
	.dbg	line, "hello.c", 61
	lda     #$03
	jsr     _cputc
;
; cvlinexy (XSize - 1, 1, YSize - 2);
;
	.dbg	line, "hello.c", 64
	jsr     decsp2
	ldy     #$03
	lda     (sp),y
	sec
	sbc     #$01
	ldy     #$01
	sta     (sp),y
	tya
	dey
	sta     (sp),y
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$02
	jsr     _cvlinexy
;
; gotoxy ((XSize - strlen (Text)) / 2, YSize / 2);
;
	.dbg	line, "hello.c", 67
	ldy     #$01
	lda     (sp),y
	jsr     pusha0
	ldy     #$FF
L0059:	iny
	ldx     _Text,y
	bne     L0059
	tya
	jsr     tossuba0
	jsr     shrax1
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	lsr     a
	jsr     _gotoxy
;
; cprintf ("%s", Text);
;
	.dbg	line, "hello.c", 68
	lda     #<(L005C)
	ldx     #>(L005C)
	jsr     pushax
	lda     #<(_Text)
	ldx     #>(_Text)
	jsr     pushax
	ldy     #$04
	jsr     _cprintf
;
; cgetc ();
;
	.dbg	line, "hello.c", 80
	jsr     _cgetc
;
; clrscr ();
;
	.dbg	line, "hello.c", 85
	jsr     _clrscr
;
; return EXIT_SUCCESS;
;
	.dbg	line, "hello.c", 88
	ldx     #$00
	txa
;
; }
;
	.dbg	line, "hello.c", 89
	jmp     incsp2
	.dbg	line

.endproc

