;
; File generated by cc65 v 2.18 - Ubuntu 2.18-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.18-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "overlaydemo.c", 3179, 1615619520
	.dbg		file, "/usr/share/cc65/include/stdio.h", 6189, 1573331006
	.dbg		file, "/usr/share/cc65/include/stddef.h", 3057, 1573331006
	.dbg		file, "/usr/share/cc65/include/stdarg.h", 2913, 1573331006
	.dbg		file, "/usr/share/cc65/include/cc65.h", 5141, 1573331006
	.dbg		file, "/usr/share/cc65/include/fcntl.h", 3550, 1573331006
	.dbg		file, "/usr/share/cc65/include/unistd.h", 4309, 1573331006
	.forceimport	__STARTUP__
	.dbg		sym, "getchar", "00", extern, "_getchar"
	.dbg		sym, "printf", "00", extern, "_printf"
	.dbg		sym, "doesclrscrafterexit", "00", extern, "_doesclrscrafterexit"
	.dbg		sym, "open", "00", extern, "_open"
	.dbg		sym, "close", "00", extern, "_close"
	.dbg		sym, "read", "00", extern, "_read"
	.dbg		sym, "_OVERLAY1_LOAD__", "00", extern, "__OVERLAY1_LOAD__"
	.dbg		sym, "_OVERLAY1_SIZE__", "00", extern, "__OVERLAY1_SIZE__"
	.dbg		sym, "_OVERLAY2_LOAD__", "00", extern, "__OVERLAY2_LOAD__"
	.dbg		sym, "_OVERLAY2_SIZE__", "00", extern, "__OVERLAY2_SIZE__"
	.dbg		sym, "_OVERLAY3_LOAD__", "00", extern, "__OVERLAY3_LOAD__"
	.dbg		sym, "_OVERLAY3_SIZE__", "00", extern, "__OVERLAY3_SIZE__"
	.import		_getchar
	.import		_printf
	.import		_doesclrscrafterexit
	.import		_open
	.import		_close
	.import		_read
	.import		__OVERLAY1_LOAD__
	.import		__OVERLAY1_SIZE__
	.import		__OVERLAY2_LOAD__
	.import		__OVERLAY2_SIZE__
	.import		__OVERLAY3_LOAD__
	.import		__OVERLAY3_SIZE__
	.export		_log
	.export		_foo
	.export		_bar
	.export		_foobar
	.export		_loadfile
	.export		_main

.segment	"RODATA"

L0020:
	.byte	$4F,$70,$65,$6E,$69,$6E,$67,$20,$6F,$76,$65,$72,$6C,$61,$79,$20
	.byte	$66,$69,$6C,$65,$20,$66,$61,$69,$6C,$65,$64,$00
L0040:
	.byte	$43,$61,$6C,$6C,$69,$6E,$67,$20,$6F,$76,$65,$72,$6C,$61,$79,$20
	.byte	$33,$20,$66,$72,$6F,$6D,$20,$6D,$61,$69,$6E,$00
L0036:
	.byte	$43,$61,$6C,$6C,$69,$6E,$67,$20,$6F,$76,$65,$72,$6C,$61,$79,$20
	.byte	$32,$20,$66,$72,$6F,$6D,$20,$6D,$61,$69,$6E,$00
L0009:
	.byte	$43,$61,$6C,$6C,$69,$6E,$67,$20,$6D,$61,$69,$6E,$20,$66,$72,$6F
	.byte	$6D,$20,$6F,$76,$65,$72,$6C,$61,$79,$20,$31,$00
L000F:
	.byte	$43,$61,$6C,$6C,$69,$6E,$67,$20,$6D,$61,$69,$6E,$20,$66,$72,$6F
	.byte	$6D,$20,$6F,$76,$65,$72,$6C,$61,$79,$20,$32,$00
L0015:
	.byte	$43,$61,$6C,$6C,$69,$6E,$67,$20,$6D,$61,$69,$6E,$20,$66,$72,$6F
	.byte	$6D,$20,$6F,$76,$65,$72,$6C,$61,$79,$20,$33,$00
L002C:
	.byte	$43,$61,$6C,$6C,$69,$6E,$67,$20,$6F,$76,$65,$72,$6C,$61,$79,$20
	.byte	$31,$20,$66,$72,$6F,$6D,$20,$6D,$61,$69,$6E,$00
L003A:
	.byte	$6F,$76,$72,$6C,$64,$65,$6D,$6F,$2E,$32,$00
L0044:
	.byte	$6F,$76,$72,$6C,$64,$65,$6D,$6F,$2E,$33,$00
L0030:
	.byte	$6F,$76,$72,$6C,$64,$65,$6D,$6F,$2E,$31,$00
L0003:
	.byte	$4C,$6F,$67,$3A,$20,$25,$73,$9B,$00

; ---------------------------------------------------------------
; void __near__ log (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_log: near

	.dbg	func, "log", "00", extern, "_log"
	.dbg	sym, "msg", "00", auto, 0

.segment	"CODE"

;
; {
;
	.dbg	line, "overlaydemo.c", 33
	jsr     pushax
;
; printf ("Log: %s\n", msg);
;
	.dbg	line, "overlaydemo.c", 34
	lda     #<(L0003)
	ldx     #>(L0003)
	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	ldy     #$04
	jsr     _printf
;
; }
;
	.dbg	line, "overlaydemo.c", 35
	jmp     incsp2
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void __near__ foo (void)
; ---------------------------------------------------------------

.segment	"OVERLAY1"

.proc	_foo: near

	.dbg	func, "foo", "00", extern, "_foo"

.segment	"OVERLAY1"

;
; log ("Calling main from overlay 1");
;
	.dbg	line, "overlaydemo.c", 51
	lda     #<(L0009)
	ldx     #>(L0009)
	jmp     _log
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void __near__ bar (void)
; ---------------------------------------------------------------

.segment	"OVERLAY2"

.proc	_bar: near

	.dbg	func, "bar", "00", extern, "_bar"

.segment	"OVERLAY2"

;
; log ("Calling main from overlay 2");
;
	.dbg	line, "overlaydemo.c", 61
	lda     #<(L000F)
	ldx     #>(L000F)
	jmp     _log
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void __near__ foobar (void)
; ---------------------------------------------------------------

.segment	"OVERLAY3"

.proc	_foobar: near

	.dbg	func, "foobar", "00", extern, "_foobar"

.segment	"OVERLAY3"

;
; log ("Calling main from overlay 3");
;
	.dbg	line, "overlaydemo.c", 71
	lda     #<(L0015)
	ldx     #>(L0015)
	jmp     _log
	.dbg	line

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ loadfile (__near__ unsigned char *, __near__ void *, __near__ void *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_loadfile: near

	.dbg	func, "loadfile", "00", extern, "_loadfile"
	.dbg	sym, "name", "00", auto, 4
	.dbg	sym, "addr", "00", auto, 2
	.dbg	sym, "size", "00", auto, 0
	.dbg	sym, "file", "00", auto, -2

.segment	"CODE"

;
; {
;
	.dbg	line, "overlaydemo.c", 78
	jsr     pushax
;
; int file = open (name, O_RDONLY);
;
	.dbg	line, "overlaydemo.c", 81
	jsr     decsp4
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$01
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	ldy     #$04
	jsr     _open
	jsr     pushax
;
; if (file == -1) {
;
	.dbg	line, "overlaydemo.c", 82
	ldy     #$01
	lda     (sp),y
	cmp     #$FF
	bne     L001C
	dey
	lda     (sp),y
	cmp     #$FF
	bne     L001C
;
; log ("Opening overlay file failed");
;
	.dbg	line, "overlaydemo.c", 83
	lda     #<(L0020)
	ldx     #>(L0020)
	jsr     _log
;
; return 0;
;
	.dbg	line, "overlaydemo.c", 84
	ldx     #$00
	txa
	jmp     incsp8
;
; read (file, addr, (unsigned) size);
;
	.dbg	line, "overlaydemo.c", 86
L001C:	jsr     decsp4
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _read
;
; close (file);
;
	.dbg	line, "overlaydemo.c", 87
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _close
;
; return 1;
;
	.dbg	line, "overlaydemo.c", 99
	ldx     #$00
	lda     #$01
;
; }
;
	.dbg	line, "overlaydemo.c", 100
	jmp     incsp8
	.dbg	line

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", extern, "_main"

.segment	"CODE"

;
; log ("Calling overlay 1 from main");
;
	.dbg	line, "overlaydemo.c", 105
	lda     #<(L002C)
	ldx     #>(L002C)
	jsr     _log
;
; if (loadfile ("ovrldemo.1", _OVERLAY1_LOAD__, _OVERLAY1_SIZE__)) {
;
	.dbg	line, "overlaydemo.c", 111
	jsr     decsp4
	lda     #<(L0030)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0030)
	sta     (sp),y
	lda     #<(__OVERLAY1_LOAD__)
	ldy     #$00
	sta     (sp),y
	iny
	lda     #>(__OVERLAY1_LOAD__)
	sta     (sp),y
	lda     #<(__OVERLAY1_SIZE__)
	ldx     #>(__OVERLAY1_SIZE__)
	jsr     _loadfile
	tax
	beq     L002E
;
; foo ();
;
	.dbg	line, "overlaydemo.c", 117
	jsr     _foo
;
; log ("Calling overlay 2 from main");
;
	.dbg	line, "overlaydemo.c", 120
L002E:	lda     #<(L0036)
	ldx     #>(L0036)
	jsr     _log
;
; if (loadfile ("ovrldemo.2", _OVERLAY2_LOAD__, _OVERLAY2_SIZE__)) {
;
	.dbg	line, "overlaydemo.c", 125
	jsr     decsp4
	lda     #<(L003A)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L003A)
	sta     (sp),y
	lda     #<(__OVERLAY2_LOAD__)
	ldy     #$00
	sta     (sp),y
	iny
	lda     #>(__OVERLAY2_LOAD__)
	sta     (sp),y
	lda     #<(__OVERLAY2_SIZE__)
	ldx     #>(__OVERLAY2_SIZE__)
	jsr     _loadfile
	tax
	beq     L0038
;
; bar ();
;
	.dbg	line, "overlaydemo.c", 126
	jsr     _bar
;
; log ("Calling overlay 3 from main");
;
	.dbg	line, "overlaydemo.c", 129
L0038:	lda     #<(L0040)
	ldx     #>(L0040)
	jsr     _log
;
; if (loadfile ("ovrldemo.3", _OVERLAY3_LOAD__, _OVERLAY3_SIZE__)) {
;
	.dbg	line, "overlaydemo.c", 130
	jsr     decsp4
	lda     #<(L0044)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0044)
	sta     (sp),y
	lda     #<(__OVERLAY3_LOAD__)
	ldy     #$00
	sta     (sp),y
	iny
	lda     #>(__OVERLAY3_LOAD__)
	sta     (sp),y
	lda     #<(__OVERLAY3_SIZE__)
	ldx     #>(__OVERLAY3_SIZE__)
	jsr     _loadfile
	tax
	beq     L0042
;
; foobar ();
;
	.dbg	line, "overlaydemo.c", 131
	jsr     _foobar
;
; if (doesclrscrafterexit ()) {
;
	.dbg	line, "overlaydemo.c", 134
L0042:	jsr     _doesclrscrafterexit
	tax
;
; getchar ();
;
	.dbg	line, "overlaydemo.c", 135
	jne     _getchar
;
; }
;
	.dbg	line, "overlaydemo.c", 137
	rts
	.dbg	line

.endproc

