OPTION COMPILE ON ATARI, ATARIXL
DEFINE FLOAT PRECISION SINGLE
DIM th AS SINGLE
DIM x,y AS SINGLE 

BITMAP ENABLE (320,192,1)
RADIAN
COLOR 0, BLUE
th=0.0
xc = SCREEN WIDTH / 2
yc = SCREEN HEIGHT / 2
WHILE th<2*PI
    x=xc+50*COS(th)
    y=yc+50*SIN(th)
    PLOT x,y
    th=th+PI/20
WEND