OPTION COMPILE ON ATARIXL
BITMAP ENABLE (320,192,1)
CLS
COLOR 0, BLUE
FOR y=0 TO SCREEN HEIGHT - 1
    FOR x=0 TO SCREEN WIDTH - 1
        IF RND(SCREEN HEIGHT) < y THEN 
            PLOT x,y
        ENDIF
    NEXT x
NEXT y