OPTION COMPILE ON ATARIXL
BITMAP ENABLE (160,96,4)
CLS
COLOR 0,BLACK
DIM c(3)
c(0) = YELLOW
c(1) = GREEN
c(2) = BLUE

FOR i=0 TO 10
    r = ( SCREEN WIDTH / 4 - i*2 )
    IF r > 0 THEN
        INK c(i MOD 3)
        CIRCLE SCREEN WIDTH / 2,SCREEN HEIGHT / 2, r
    ENDIF
NEXT